RUNTIME: 3

MAXWELL_PARAMS:
  ELEC_ARRAY:
    FPATH_CFG: "dummy.cfg"
  SAMPLE_STREAM:
    N_SAMPLES: 1000
    CHANNELS: 1024
  UNIFIED_STIMULATOR:
    CHAN_ID: [1,2,3,4]
    AMP_MV: 400
    FREQ_HZ: 100
